{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glycol.fullname" . }}-credentials
  labels:
    {{- include "glycol.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.json: |
    {
      "client_id": {{ .Values.credentials.clientId | quote }},
      "client_secret": {{ .Values.credentials.clientSecret | quote }}
    }
{{- end }}
