{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glycol.secretName" . }}
  labels:
    {{- include "glycol.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.existingSecretKey }}: |
    {
      "clientId": {{ .Values.credentials.clientId | quote }},
      "clientSecret": {{ .Values.credentials.clientSecret | quote }}
    }
{{- end }}
