apiVersion: v1
kind: Service
metadata:
  name: glycol-web
  namespace: glycol
  labels:
    app: glycol-web
spec:
  type: ClusterIP
  selector:
    app: glycol-web
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  sessionAffinity: None
